Scoverage
mohammadSalameh06/PipelineExecution pull request #2
Opened 2024-08-02 09:49 UTC by mohammadSalameh06

2024-08-06 10:56 UTC, abdalrahmanSrour commented
Please update the title to have what are you changing in this PR, also you should add description to it with more details and a screen shot with coverage report.

2024-08-06 11:02 UTC, abdalrahmanSrour requested changes

2024-08-06 11:02 UTC, abdalrahmanSrour commented on .bsp/sbt.json
> -{"name":"sbt","version":"1.10.0","bspVersion":"2.1.0-M1","languages":["scala"],"argv":["C:\\Users\\user\\AppData\\Local\\Coursier\\cache\\arc\\https\\github.com\\adoptium\\temurin17-binaries\\release
I think this file should be ignored, also add `.idea` folder and `.bsp` folder.

2024-08-06 11:02 UTC, abdalrahmanSrour commented on build.sbt
> +coverageExcludedFiles := "ae.network.migration.pipeline.processExecute.MainTest" // Exclude test files
You should exclude main not the test file.

2024-08-06 11:02 UTC, abdalrahmanSrour commented on src/main/scala/ae/network/migration/pipeline/parser/ParserJson.scala
> +  import io.circe.jawn.decode
Please remove extra spaces before `import` keyword

2024-08-06 11:02 UTC, abdalrahmanSrour commented on src/main/scala/ae/network/migration/pipeline/processExcute/PipelineProcessor.scala
> +  import scala.concurrent.{Future, ExecutionContext}
Same as above.

2024-08-06 11:02 UTC, abdalrahmanSrour commented on src/test/scala/ae/network/migration/pipeline/MainTest.scala
> +//package ae.network.migration.pipeline
Delete this file.

2024-08-06 16:41 UTC, mohammadSalameh06 commented on build.sbt
> +coverageExcludedFiles := "ae.network.migration.pipeline.processExecute.MainTest" // Exclude test files
Done

2024-08-06 16:42 UTC, mohammadSalameh06 commented on src/main/scala/ae/network/migration/pipeline/parser/ParserJson.scala
> +  import io.circe.jawn.decode
Done

2024-08-06 16:42 UTC, mohammadSalameh06 commented on src/test/scala/ae/network/migration/pipeline/MainTest.scala
> +//package ae.network.migration.pipeline
done

2024-08-06 16:53 UTC, mohammadSalameh06 commented
@abdalrahmanSrour all the requested changes are done , can you please check if the **bsp and idea**  are deleted or not.
thanks

2024-08-08 09:17 UTC, abdalrahmanSrour approved these changes

2024-08-23 08:38 UTC, merged